repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args: [--py311-plus]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    args: [--extend-ignore=E501]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
    exclude: ^tests/integration
  - id: requirements-txt-fixer
  - id: file-contents-sorter
    files: \.(docker|git)ignore
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
