[tool.isort]
add_imports = [
    "from __future__ import annotations"
]
force_single_line = true
profile = "black"

[tool.coverage.run]
plugins = ["covdefaults"]

[tool.coverage.report]
fail_under = 1
