[tool.isort]
add_imports = [
    "from __future__ import annotations"
]
force_single_line = true
profile = "black"

[tool.coverage.run]
plugins = ["covdefaults"]

[tool.coverage.report]
fail_under = 1

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
extend-select = [
    "E",
    "F",
    "W",
    "UP",
    "B",
    "SIM",
    "PT",
    "D",
    "N",
    "FBT",
    "A",
    "C4",
    "DTZ",
    "ISC",
    "LOG",
    "INP",
    "PIE",
    "RSE",
    "SLF",
    "SLOT",
    "TID",
    "TCH",
    "ARG",
    "TD",
    "ERA",
    "PGH",
    "TRY",
    "FLY",
    "FURB",
    "RUF",
]
ignore = [
    "D100",
    "D103",
    "D104",
    "D107",
    "D203",
    "D213",
    "E501",
    "ISC001",
    "RUF001",
]
