line-length = 100

[format]
quote-style = "single"

[lint]
extend-select = [
    "E",
    "F",
    "W",
    "UP",
    "B",
    "SIM",
    "PT",
    "D",
    "N",
    "FBT",
    "A",
    "C4",
    "DTZ",
    "ISC",
    "LOG",
    "INP",
    "PIE",
    "RSE",
    "SLF",
    "SLOT",
    "TID",
    "TCH",
    "ARG",
    "TD",
    "ERA",
    "PGH",
    "TRY",
]
ignore = [
    "D100",
    "D103",
    "D104",
    "D107",
    "D203",
    "D213",
    "E501",
    "ISC001",
]
