line-length = 100

[format]
quote-style = "single"

[lint]
extend-select = ["E", "F", "W", "UP", "B", "SIM", "PT", "D", "N", "FBT", "A", "C4"]
ignore = ["E501", "D100", "D103", "D104", "D203", "D213"]
